### ISSUE TITLE
Crash on code generation

### ISSUE THREAD

**Issue by aliktab** [JetClient/jet-client-support#119] opened 2024-11-17 21:03 UTC
Crash on code generation

**Environment information:**
- OS: Mac OS 15.1
- IDE version: 2024.3, Build #PY-243.21565.199, built on November 13, 2024
- plugin version: 2024.3.15-243

LOG:
java.util.ServiceConfigurationError: com.oracle.truffle.api.library.DefaultExportProvider: com.oracle.truffle.object.DynamicObjectLibraryImplGen$DynamicObjectLibraryProvider not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.loadServices(EngineAccessor.java:351)
	at com.oracle.truffle.api.library.LibraryFactory.loadExternalDefaultProviders(LibraryFactory.java:434)
	at com.oracle.truffle.api.library.LibraryFactory.getExternalDefaultProviders(LibraryFactory.java:425)
	at com.oracle.truffle.api.library.LibraryFactory.initDefaultExports(LibraryFactory.java:213)
	at com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:208)
	at com.oracle.truffle.api.library.DynamicDispatchLibraryGen.<init>(DynamicDispatchLibraryGen.java:33)
	at com.oracle.truffle.api.library.DynamicDispatchLibraryGen.<clinit>(DynamicDispatchLibraryGen.java:25)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:770)
	at com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:751)
	at com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:744)
	at com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:202)
	at com.oracle.truffle.api.interop.InteropLibraryGen.<init>(InteropLibraryGen.java:180)
	at com.oracle.truffle.api.interop.InteropLibraryGen.<clinit>(InteropLibraryGen.java:171)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:770)
	at com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:751)
	at com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:744)
	at com.oracle.truffle.api.interop.InteropLibrary.<clinit>(InteropLibrary.java:2972)
	at com.oracle.truffle.polyglot.PolyglotValueDispatch.<clinit>(PolyglotValueDispatch.java:168)
	at com.oracle.truffle.polyglot.PolyglotImpl.initialize(PolyglotImpl.java:202)
	at org.graalvm.polyglot.Engine.loadAndValidateProviders(Engine.java:1691)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:1717)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:1712)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:1712)
	at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:170)
	at org.graalvm.polyglot.Engine.getImpl(Engine.java:422)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:724)
	at io.jetclient.gw.b(SourceFile:39)
	at io.jetclient.rT.a(SourceFile:12)
	at io.jetclient.gw.c(SourceFile:35)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.jetclient.gw.a(SourceFile:34)
	at io.jetclient.gw.a(SourceFile:45)
	at io.jetclient.gw.a(SourceFile:64)
	at io.jetclient.f.a(SourceFile:658)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$executeOnPooledThread$1.run(AnyThreadWriteThreadingSupport.kt:167)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.intellij.util.concurrency.ContextCallable.lambda$call$1(ContextCallable.java:74)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:83)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by AntonShuvaev** [comment] 2024-11-18 16:55
Thanks for reporting this! I've released an update (version 2024.3.16). Please let me know if it resolves the issue.

**Comment by mebius-san** [comment] 2024-11-19 12:22
No, bug is still here for my serevrs
LOG:

java.util.ServiceConfigurationError: com.oracle.truffle.api.library.DefaultExportProvider: com.oracle.truffle.object.DynamicObjectLibraryImplGen$DynamicObjectLibraryProvider not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.loadServices(EngineAccessor.java:351)
	at com.oracle.truffle.api.library.LibraryFactory.loadExternalDefaultProviders(LibraryFactory.java:434)
	at com.oracle.truffle.api.library.LibraryFactory.getExternalDefaultProviders(LibraryFactory.java:425)
	at com.oracle.truffle.api.library.LibraryFactory.initDefaultExports(LibraryFactory.java:213)
	at com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:208)
	at com.oracle.truffle.api.library.DynamicDispatchLibraryGen.<init>(DynamicDispatchLibraryGen.java:33)
	at com.oracle.truffle.api.library.DynamicDispatchLibraryGen.<clinit>(DynamicDispatchLibraryGen.java:25)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:770)
	at com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:751)
	at com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:744)
	at com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:202)
	at com.oracle.truffle.api.interop.InteropLibraryGen.<init>(InteropLibraryGen.java:180)
	at com.oracle.truffle.api.interop.InteropLibraryGen.<clinit>(InteropLibraryGen.java:171)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:770)
	at com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:751)
	at com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:744)
	at com.oracle.truffle.api.interop.InteropLibrary.<clinit>(InteropLibrary.java:2972)
	at com.oracle.truffle.polyglot.PolyglotValueDispatch.<clinit>(PolyglotValueDispatch.java:168)
	at com.oracle.truffle.polyglot.PolyglotImpl.initialize(PolyglotImpl.java:202)
	at org.graalvm.polyglot.Engine.loadAndValidateProviders(Engine.java:1691)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:1717)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:1712)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:1712)
	at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:170)
	at org.graalvm.polyglot.Engine.getImpl(Engine.java:422)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:724)
	at io.jetclient.gm.b(SourceFile:148)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.jetclient.gm.a(SourceFile:144)
	at io.jetclient.gm.a(SourceFile:249)
	at io.jetclient.gm.a(SourceFile:222)
	at io.jetclient.rT.a(SourceFile:12)
	at io.jetclient.gm.a(SourceFile:221)
	at io.jetclient.r.a(SourceFile:327)
	at io.jetclient.r$e.run(SourceFile:289)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$7(CoreProgressManager.java:542)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by mebius-san** [comment] 2024-11-19 12:23
For the draft with google it now is saying: Target host is not specified.
![Screenshot 2024-11-19 at 16 23 14](https://github.com/user-attachments/assets/f904e4af-cea0-4378-842a-814d3efcea4b)

**Comment by AntonShuvaev** [comment] 2024-11-19 12:34
@mebius-san, thank you for providing the details. I’ll investigate further.

**Comment by mebius-san** [comment] 2024-11-19 17:17
=== Plugins ===
Custom plugins: [Dash (3.3), OpenSCAD Language Support (2.4.0), Key Promoter X (2024.2.2), JetBrains AI Assistant (243.21565.212), GitLab (243.21565.204), GitHub (243.21565.204-ultimate), BinEd - Binary/Hex Editor (0.2.10.1), Big Data Tools Core (243.21565.211), Big Data File Viewer (243.21565.129), GraphQL (243.21565.122), .ignore (4.5.4), github-copilot-intellij (1.5.29.7524), JetClient - The Ultimate REST Client (2024.3.16-243)]
Disabled plugins:[Zeppelin (243.21565.129), Properties (243.21565.199), EmmyLua (1.4.14-IDEA242), Remote File Systems (243.21565.211), Big Data Tools (243.21565.129)]

**Comment by AntonShuvaev** [comment] 2024-11-20 13:16
@aliktab, @mebius-san, I’ve released a new version 2024.3.17 with a fix for this issue. Please update to the latest version and let me know if the problem is resolved.

**Comment by mebius-san** [comment] 2024-11-23 20:40
Still doesn't work. 
Host not specified error for www.google.com now.

**Comment by mebius-san** [comment] 2024-11-23 20:48
ok, now it is working, thank you.

**Closed** 2024-11-23 20:49 UTC
Labels: bug
