### ISSUE TITLE
Deserialization error on Azure JWT Token acquire

### ISSUE THREAD

**Issue by is-smok** [JetClient/jet-client-support#109] opened 2024-09-30 12:10 UTC
**Describe the bug**
Error raised at the end of token retrieval from Azure. 
_`Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`) at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 278] (through reference chain: java.util.LinkedHashMap["error_codes"])`_

The error MIGHT be caused by SSL cert rewritten by proxy.

**Steps to reproduce**
Acquire token from Azure in network protected by proxy that rewrites SSL cert for a webpage

**Expected behavior**
I'm able to request JWT from Azure EntraID. Tool should use certs from MS Cert Store or make it feasible to provide cert chain manually.

**Environment information:**
- OS: Win 11
- IDE version: 2024.1.6
- plugin version: 2024.3.11-241

**Comment by AntonShuvaev** [comment] 2024-09-30 12:48
Thanks for reporting this issue. Could you provide more details? Specifically, where do you see this error? Do you have any pre-request or post-response scripts?

**Comment by is-smok** [comment] 2024-09-30 13:18
Please find attached picture. After I click "Get New Access Token" auth window opens, I accept account to be used, windows is closed, looks like JetClient gets new JWT in background and then the message appears. I am not using any additional scripts.

**Comment by AntonShuvaev** [comment] 2024-09-30 16:51
Thanks for the details. I'll fix it ASAP.

**Comment by AntonShuvaev** [comment] 2024-10-02 06:15
The issue is fixed in version 2024.3.12. Let me know if you encounter any problems.

**Closed by AntonShuvaev** 2024-10-02 06:15 UTC
Labels: bug
